project:
  type: book

book:
  title: "Notes on Bayesian Stats"
  author: "Eric Ekholm"
  date: "12/18/2023"
  chapters:
    - index.qmd
    - ch1_intro.qmd
    - ch2_beta_binomial.qmd
    - ch3_gamma_poisson.qmd
    - ch4_posterior_simulation.qmd
    - distributions.qmd

format:
  html:
    theme: cosmo



