project:
  type: book

book:
  title: "Notes on Bayesian Stats"
  author: "Eric Ekholm"
  date: "12/18/2023"
  chapters:
    - index.qmd
    - ch1_intro.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



